### ISSUE TITLE
Cannot customize tutorial?

### ISSUE THREAD

**Issue by wilbowma** [Multitallented/Civs#122]
Civs version: 1.6.7
Minecraft: 1.15.2

I'm trying to customize the tutorial to remove or decrease rewards, and have changed `tutorial.yml` to the following. However, the changes seem to be ignored and I still receive the commented out items after building a shelter, and money after depositing the items in the shelter.
```
default:
  steps:
    - type: build
      region: shelter
      rewards:
        # commands:
        #   - ^!give DIRT 4
        # permissions:
        #   - civs.shop
        #items:
        #  - BEEF*32
        #  - BREAD*4
        #  - CARROT*32
        #  - POTATO*32
    - type: upkeep
      region: shelter
      rewards:
        money: 0
    - type: buy
      region: coal_shop
    - type: build
      region: coal_shop
```
